---
title: "Class 12: Bioinformatics in drug discovery and design"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Section 1: *In silico* docking of drugs to HIV-1 protease

### 1. Obtaining and inspecting our input structure.

```{r}
library(bio3d)
file.name <- get.pdb("1hsg")
```

```{r}
hiv <- read.pdb(file.name)
```

```{r}
hiv
```

### 2. Prepare initial protein and ligand input files

```{r}
prot <- trim.pdb(hiv, "protein")
lig <- trim.pdb(hiv, "ligand")
```

```{r}
write.pdb(prot, file = "1hsg_protein.pdb")
write.pdb(lig, file = "1hsg_ligand.pdb")
```

## Section 2: Docking ligands into HIV-1 protease

### 3. Inspecting your docking results

```{r}
res <- read.pdb("all.pdbqt", multi=TRUE)
write.pdb(res, "results.pdb")
```

```{r}
ori <- read.pdb("ligand.pdbqt")
rmsd(ori, res)
```

## Section 3. Exploring the conformational dynamics of proteins

### 1. Normal Mode Analysis (NMA)

```{r}
library(bio3d)
pdb <- read.pdb("1HEL")
modes <- nma(pdb)
plot(modes, sse=pdb)
```

```{r}
# Visualize NMA results
mktrj(modes, mode=7, file="nma_7.pdb")
```
